IamPolicyScrapingDetail:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsScrapingDetailProd"
            - "RestaurantsScrapingDetailDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                      - !GetAtt "LambdaHandlerSchedules.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:ListBucket"
                  Resource: !Sub "arn:aws:s3:::${S3Images}"
                - Effect: "Allow"
                  Action:
                      - "s3:DeleteObject"
                      - "s3:PutObject"
                  Resource: !Sub "arn:aws:s3:::${S3Images}/images/*"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:GetItem"
                      - "dynamodb:PutItem"
                  Resource: !GetAtt "DynamodbRestaurants.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:DeleteItem"
                  Resource: !GetAtt "DynamodbRestaurantsTasks.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:DeleteItem"
                      - "dynamodb:BatchWriteItem"
                  Resource: !GetAtt "DynamodbRestaurantsImages.Arn"
                - Effect: "Allow"
                  Action:
                      - "ssm:GetParameter"
                  Resource: !If
                      - "IsProd"
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/google/geocoding/prod/key"
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/google/geocoding/dev/key"
        Roles:
            - !Ref "IamRoleScrapingDetail"