IamPolicyScrapingDetail:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsRegisterTasksTmpScrapingDetailProd"
            - "RestaurantsRegisterTasksTmpScrapingDetailDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaErrorCommon.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:GetItem"
                      - "dynamodb:PutItem"
                  Resource: !GetAtt "DynamodbRestaurants.Arn"
        Roles:
            - !Ref "IamRoleScrapingDetail"