LambdaScrapingDetail:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/scraping_detail/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsScrapingDetailProd"
            - "RestaurantsScrapingDetailDev"
        Role: !GetAtt "IamRoleScrapingDetail.Arn"
        Runtime: "python3.12"
        Layers:
            - !Ref "LambdaLayerDynamodbTypes"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                ARN_LAMBDA_HANDLER_SCHEDULES: !GetAtt "LambdaHandlerSchedules.Arn"
                NAME_IMAGES_BUCKET: !Ref "S3Images"
                NAME_TASK_SCRAPING_DETAIL: !Ref "TaskNameScrapingDetail"
                NAME_DYNAMODB_RESTAURANTS: !Ref "DynamodbRestaurants"
                NAME_DYNAMODB_TABLE_TASKS: !Ref "DynamodbRestaurantsTasks"
                NAME_PARAMETER_API_KEY_GOOGLE_GEOCODING: !If
                    - "IsProd"
                    - "/google/geocoding/prod/key"
                    - "/google/geocoding/dev/key"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 120