IamPolicyInvokeHandlerSchedules:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsInvokeHandlerSchedulesProd"
            - "RestaurantsInvokeHandlerSchedulesDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaHandlerSchedules.Arn"
        Roles:
            - !Ref "IamRoleInvokeHandlerSchedules"