AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
    # デプロイ先環境の設定
    EnvironmentType:
        Type: "String"
        AllowedValues: ["dev", "prod"]

Conditions:
    # 本番環境かどうか
    IsProd: !Equals [!Ref "EnvironmentType", "prod"]

Resources:
    # Lambdaレイヤー - check_area_code_names
    - $file: resources/lambda_layers/check_area_code_names.yml

    # Lambda - LINE通知
    - $file: resources/line_notify/lambda.yml
    - $file: resources/line_notify/iam_role.yml
    - $file: resources/line_notify/iam_policy.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/invoke_register_task_scraping_abstract_small_areas/iam_role.yml
    - $file: resources/invoke_register_task_scraping_abstract_small_areas/iam_policy.yml

    # Lambda - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/register_tasks_tmp_scraping_abstract_small_areas/lambda.yml
    - $file: resources/register_tasks_tmp_scraping_abstract_small_areas/iam_role.yml
    - $file: resources/register_tasks_tmp_scraping_abstract_small_areas/iam_policy.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/invoke_register_task_scraping_abstract_pages/iam_role.yml
    - $file: resources/invoke_register_task_scraping_abstract_pages/iam_policy.yml

    # Lambda - 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/register_task_scraping_abstract_pages/lambda.yml
    - $file: resources/register_task_scraping_abstract_pages/iam_role.yml
    - $file: resources/register_task_scraping_abstract_pages/iam_policy.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/invoke_scraping_abstract/iam_role.yml
    - $file: resources/invoke_scraping_abstract/iam_policy.yml

    # Lambda - 概要情報スクレイピング
    - $file: resources/scraping_abstract/lambda.yml
    - $file: resources/scraping_abstract/iam_role.yml
    - $file: resources/scraping_abstract/iam_policy.yml

    # EventBridgeスケジュールグループ
    - $file: resources/eventbridge/schedule_group.yml

    # DynamoDB
    - $file: resources/dynamodb/restaurants.yml
    - $file: resources/dynamodb/restaurants_areas.yml
    - $file: resources/dynamodb/restaurants_tasks_tmp.yml

Outputs:
    # LINE通知LambdaのARN
    ArnLambdaLineNotify:
        Value: !GetAtt "LambdaLineNotify.Arn"
        Export:
            Name: "ARN-LambdaLineNotify"

    # 概要情報スクレイピングタスクの登録（小エリアごと）LambdaのARN
    ArnLambdaRegisterTasksTmpScrapingAbstractSmallAreas:
        Value: !GetAtt "LambdaRegisterTasksTmpScrapingAbstractSmallAreas.Arn"
        Export:
            Name: "ARN-LambdaRegisterTasksTmpScrapingAbstractSmallAreas"

    # 概要情報スクレイピングタスクの登録（ページごと）LambdaのARN
    ArnLambdaRegisterTaskScrapingAbstractPages:
        Value: !GetAtt "LambdaRegisterTaskScrapingAbstractPages.Arn"
        Export:
            Name: "ARN-LambdaRegisterTaskScrapingAbstractPages"

    # 概要情報スクレイピングLambdaのARN
    ArnLambdaScrapingAbstract:
        Value: !GetAtt "LambdaScrapingAbstract.Arn"
        Export:
            Name: "ARN-LambdaScrapingAbstract"