AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
    # デプロイ先環境の設定
    EnvironmentType:
        Type: "String"
        AllowedValues: ["dev", "prod"]

Conditions:
    # 本番環境かどうか
    IsProd: !Equals [!Ref "EnvironmentType", "prod"]

Resources:
    # Lambda - LINE通知
    - $file: resources/lambda/line_notify.yml
    - $file: resources/iam/role/line_notify.yml
    - $file: resources/iam/policy/line_notify.yml

    # Lambda - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/lambda/register_task_scraping_abstract_small_areas.yml
    - $file: resources/iam/role/register_task_scraping_abstract_small_areas.yml
    - $file: resources/iam/policy/register_task_scraping_abstract_small_areas.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/iam/role/invoke_register_task_scraping_abstract_small_areas.yml
    - $file: resources/iam/policy/invoke_register_task_scraping_abstract_small_areas.yml

    # 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/lambda/register_task_scraping_abstract_pages.yml
    - $file: resources/iam/role/register_task_scraping_abstract_pages.yml
    - $file: resources/iam/policy/register_task_scraping_abstract_pages.yml

    # EventBridgeスケジュールグループ
    - $file: resources/eventbridge/group.yml

    # DynamoDB
    - $file: resources/dynamodb/restaurants.yml
    - $file: resources/dynamodb/restaurants_areas.yml

Outputs:
    # LINE通知LambdaのARN
    ArnLambdaLineNotify:
        Value: !GetAtt "LambdaLineNotify.Arn"
        Export:
            Name: "ARN-LambdaLineNotify"

    # 概要情報スクレイピングタスクの登録（小エリアごと）LambdaのARN
    ArnLambdaRegisterTaskScrapingAbstractSmallAreas:
        Value: !GetAtt "LambdaRegisterTaskScrapingAbstractSmallAreas.Arn"
        Export:
            Name: "ARN-LambdaRegisterTaskScrapingAbstractSmallAreas"

    # 概要情報スクレイピングタスクの登録（ページごと）LambdaのARN
    ArnLambdaRegisterTaskScrapingAbstractPages:
        Value: !GetAtt "LambdaRegisterTaskScrapingAbstractPages.Arn"
        Export:
            Name: "ARN-LambdaRegisterTaskScrapingAbstractPages"