AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
    # デプロイ先環境の設定
    EnvironmentType:
        Type: "String"
        AllowedValues: ["dev", "prod"]

    # タスク名 - ページごとのタスク登録
    TaskNameRegisterPages:
        Type: "String"
        Default: "RegisterPages"

    # タスク名 - 概要情報スクレイピング
    TaskNameScrapingAbstract:
        Type: "String"
        Default: "ScrapingAbstract"

    # タスク名 - 詳細情報スクレイピング
    TaskNameScrapingDetail:
        Type: "String"
        Default: "ScrapingDetail"

Conditions:
    # 本番環境かどうか
    IsProd: !Equals [!Ref "EnvironmentType", "prod"]

Resources:
    # S3エラーログ用バケット
    - $file: resources/s3/error_logs.yml

    # Lambdaレイヤー - エリア構造体
    - $file: resources/lambda_layers/ds_area.yml

    # Lambdaレイヤー - dynamodb_types
    - $file: resources/lambda_layers/dynamodb_types.yml

    # EventBridgeスケジュールグループ
    - $file: resources/eventbridge/schedule_group.yml

    # Lambda - LINE通知
    - $file: resources/line_notify/lambda.yml
    - $file: resources/line_notify/iam_role.yml
    - $file: resources/line_notify/iam_policy.yml

    # Lambda - エラー共通処理
    - $file: resources/error_common/lambda.yml
    - $file: resources/error_common/iam_role.yml
    - $file: resources/error_common/iam_policy.yml

    # Lambda - スケジュール管理
    - $file: resources/handler_schedules/lambda.yml
    - $file: resources/handler_schedules/iam_role.yml
    - $file: resources/handler_schedules/iam_policy.yml

    # EventBridge - スケジュール登録
    - $file: resources/invoke_handler_schedules/iam_role.yml
    - $file: resources/invoke_handler_schedules/iam_policy.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/invoke_register_small_areas/iam_role.yml
    - $file: resources/invoke_register_small_areas/iam_policy.yml

    # Lambda - 概要情報スクレイピングタスクの登録（小エリアごと）
    - $file: resources/register_small_areas/lambda.yml
    - $file: resources/register_small_areas/iam_role.yml
    - $file: resources/register_small_areas/iam_policy.yml

    # EventBridge - 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/invoke_register_pages/iam_role.yml
    - $file: resources/invoke_register_pages/iam_policy.yml

    # Lambda - 概要情報スクレイピングタスクの登録（ページごと）
    - $file: resources/register_pages/lambda.yml
    - $file: resources/register_pages/iam_role.yml
    - $file: resources/register_pages/iam_policy.yml

    # EventBridge - 概要情報スクレイピング
    - $file: resources/invoke_scraping_abstract/iam_role.yml
    - $file: resources/invoke_scraping_abstract/iam_policy.yml

    # Lambda - 概要情報スクレイピング
    - $file: resources/scraping_abstract/lambda.yml
    - $file: resources/scraping_abstract/iam_role.yml
    - $file: resources/scraping_abstract/iam_policy.yml

    # EventBridge - 詳細情報スクレイピング
    - $file: resources/invoke_scraping_detail/iam_role.yml
    - $file: resources/invoke_scraping_detail/iam_policy.yml

    # Lambda - 詳細情報スクレイピング
    - $file: resources/scraping_detail/lambda.yml
    - $file: resources/scraping_detail/iam_role.yml
    - $file: resources/scraping_detail/iam_policy.yml

    # Lambda - 新規の飲食店通知
    - $file: resources/notify_new_restaurants/lambda.yml
    - $file: resources/notify_new_restaurants/iam_role.yml
    - $file: resources/notify_new_restaurants/iam_policy.yml

    # EventBridge - 新規の飲食店通知
    - $file: resources/invoke_notify_new_restaurants/iam_role.yml
    - $file: resources/invoke_notify_new_restaurants/iam_policy.yml

    # DynamoDB
    - $file: resources/dynamodb/restaurants.yml
    - $file: resources/dynamodb/restaurants_areas.yml
    - $file: resources/dynamodb/restaurants_tasks.yml

Outputs:
    # LINE通知LambdaのARN
    ArnLambdaLineNotify:
        Value: !GetAtt "LambdaLineNotify.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaLineNotify"

    # エラー共通処理LambdaのARN
    ArnLambdaErrorCommon:
        Value: !GetAtt "LambdaErrorCommon.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaErrorCommon"

    # スケジュール登録LambdaのARN
    ArnLambdaHandlerSchedules:
        Value: !GetAtt "LambdaHandlerSchedules.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaRegisterSchedule"

    # 概要情報スクレイピングタスクの登録（小エリアごと）LambdaのARN
    ArnLambdaRegisterSmallAreas:
        Value: !GetAtt "LambdaRegisterSmallAreas.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaRegisterSmallAreas"

    # 概要情報スクレイピングタスクの登録（ページごと）LambdaのARN
    ArnLambdaRegisterPages:
        Value: !GetAtt "LambdaRegisterPages.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaRegisterPages"

    # 概要情報スクレイピングLambdaのARN
    ArnScrapingAbstract:
        Value: !GetAtt "LambdaScrapingAbstract.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-ScrapingAbstract"

    # 詳細情報スクレイピングLambdaのARN
    ArnScrapingDetail:
        Value: !GetAtt "LambdaScrapingDetail.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-ScrapingDetail"

    # 新規の飲食店通知LambdaのARN
    ArnNotifyNewRestaurants:
        Value: !GetAtt "LambdaNotifyNewRestaurants.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-NotifyNewRestaurants"