LambdaRegisterSmallAreas:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/register_small_areas/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsRegisterSmallAreasProd"
            - "RestaurantsRegisterSmallAreasDev"
        Role: !GetAtt "IamRoleRegisterSmallAreas.Arn"
        Runtime: "python3.10"
        Layers:
            - !Ref "LambdaLayerDynamodbTypes"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                ARN_LAMBDA_REGISTER_TASK_SCRAPING_ABSTRAT_PAGES: !GetAtt "LambdaRegisterAbstractPages.Arn"
                NAME_DYNAMODB_TABLE_TASKS_TMP: !Ref "DynamodbRestaurantsTasksTmp"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30

        Events:
            EventBridgeScheduleLambdaRegisterSmallAreas:
                Type: "ScheduleV2"
                Properties:
                    ScheduleExpression: cron(0 0 ? * SUN *)
                    ScheduleExpressionTimezone: "Asia/Tokyo"
                    State: ENABLED
                    GroupName: !Ref "EventBridgeScheduleGroup"
                    Name: !If
                        - "IsProd"
                        - "RestaurantsLambdaRegisterSmallAreasProd"
                        - "RestaurantsLambdaRegisterSmallAreasDev"
                    RoleArn: !GetAtt "IamRoleInvokeRegisterSmallAreas.Arn"
                    Input: '{"middle_area_code": "Y883"}'