IamPolicyRegisterTaskScrapingAbstractSmallAreas:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsRegisterTaskScrapingAbstractSmallAreasProd"
            - "RestaurantsRegisterTaskScrapingAbstractSmallAreasDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "ssm:GetParameter"
                  Resource:
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/restaurants/api_key/hotpepper"
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - "scheduler:CreateSchedule"
                  Resource: "*"
        Roles:
            - !Ref "IamRoleRegisterTaskScrapingAbstractSmallAreas"