# IAMロール
IamRoleInvokeRegisterSmallAreas:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsInvokeRegisterSmallAreasProd"
            - "RestaurantsInvokeRegisterSmallAreasDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "scheduler.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyInvokeRegisterSmallAreas:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsInvokeRegisterSmallAreasProd"
            - "RestaurantsInvokeRegisterSmallAreasDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaRegisterSmallAreas.Arn"
        Roles:
            - !Ref "IamRoleInvokeRegisterSmallAreas"