# IAMロール
IamRoleInvokeScrapingAbstract:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsInvokeScrapingAbstractProd"
            - "RestaurantsInvokeScrapingAbstractDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "scheduler.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyInvokeScrapingAbstract:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsInvokeScrapingAbstractProd"
            - "RestaurantsInvokeScrapingAbstractDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaScrapingAbstract.Arn"
        Roles:
            - !Ref "IamRoleInvokeScrapingAbstract"