IamPolicyNotifyNewRestaurants:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsNotifyNewRestaurantsProd"
            - "RestaurantsNotifyNewRestaurantsDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                      - !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:BatchWriteItem"
                  Resource:
                      - !GetAtt "DynamodbRestaurants.Arn"
                      - !Sub "${DynamodbRestaurants.Arn}/index/IsNotifiedIndex"
                      - !Sub "${DynamodbRestaurants.Arn}/index/LatitudeIndex" # 仮
        Roles:
            - !Ref "IamRoleNotifyNewRestaurants"