LambdaNotifyNewRestaurants:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/notify_new_restaurants/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsNotifyNewRestaurantsProd"
            - "RestaurantsNotifyNewRestaurantsDev"
        Role: !GetAtt "IamRoleNotifyNewRestaurants.Arn"
        Runtime: "python3.10"
        Layers:
            - !Ref "LambdaLayerDynamodbTypes"
        Environment:
            Variables:
                ARN_LAMBDA_LINE_NOTIFY: !GetAtt "LambdaLineNotify.Arn"
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                NAME_DYNAMODB_RESTAURANTS: !Ref "DynamodbRestaurants"
                NAME_DYNAMODB_GSI_RESTAURANTS: "IsNotifiedIndex"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30

        Events:
            EventBridgeScheduleLambdaNotifyNewRestaurants:
                Type: "ScheduleV2"
                Properties:
                    ScheduleExpression: cron(0 0 ? * SAT *)
                    ScheduleExpressionTimezone: "Asia/Tokyo"
                    State: ENABLED
                    GroupName: !Ref "EventBridgeScheduleGroup"
                    Name: !If
                        - "IsProd"
                        - "NotifyNewRestaurantsProd"
                        - "NotifyNewRestaurantsDev"
                    RoleArn: !GetAtt "IamRoleInvokeNotifyNewRestaurants.Arn"