IamPolicyScrapingAbstract:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsScrapingAbstractProd"
            - "RestaurantsScrapingAbstractDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                      - !GetAtt "LambdaHandlerSchedules.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:PutObject"
                  Resource: !Sub "arn:aws:s3:::${S3Images}/thumbnails/*"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:BatchGetItem"
                      - "dynamodb:BatchWriteItem"
                  Resource: !GetAtt "DynamodbRestaurants.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:DeleteItem"
                      - "dynamodb:BatchWriteItem"
                  Resource:
                      - !GetAtt "DynamodbRestaurantsTasks.Arn"
        Roles:
            - !Ref "IamRoleScrapingAbstract"