IamPolicyScrapingAbstract:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsScrapingAbstractProd"
            - "RestaurantsScrapingAbstractDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - "scheduler:CreateSchedule"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:BatchGetItem"
                      - "dynamodb:BatchWriteItem"
                  Resource: !GetAtt "DynamodbRestaurants.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:BatchWriteItem"
                  Resource: !GetAtt "DynamodbRestaurantsAreas.Arn"
        Roles:
            - !Ref "IamRoleScrapingAbstract"