LambdaScrapingAbstract:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/scraping_abstract/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsScrapingAbstractProd"
            - "RestaurantsScrapingAbstractDev"
        Role: !GetAtt "IamRoleScrapingAbstract.Arn"
        Runtime: "python3.10"
        Environment:
            Variables:
                ARN_LAMBDA_LINE_NOTIFY: !GetAtt "LambdaLineNotify.Arn"
                SCHEDULE_GROUP_NAME: !Ref "EventBridgeScheduleGroup"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30