IamRoleInvokeRegisterTaskScrapingAbstractPages:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsInvokeRegisterTaskScrapingAbstractPagesProd"
            - "RestaurantsInvokeRegisterTaskScrapingAbstractPagesDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "scheduler.amazonaws.com"
                  Action: "sts:AssumeRole"