LambdaRegisterPages:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/register_pages/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsRegisterPagesProd"
            - "RestaurantsRegisterPagesDev"
        Role: !GetAtt "IamRoleRegisterPages.Arn"
        Runtime: "python3.10"
        Layers:
            - !Ref "LambdaLayerDynamodbTypes"
            - !Ref "LambdaLayerCheckAreaCodeNames"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                ARN_LAMBDA_SCRAPING_ABSTRACT: !GetAtt "LambdaScrapingAbstract.Arn"
                ARN_IAM_ROLE_INVOKE_SCRAPING_ABSTRACT: !GetAtt "IamRoleInvokeScrapingAbstract.Arn"
                NAME_LAMBDA_HANDLER_SCHEDULES: !GetAtt "LambdaHandlerSchedules.Arn"
                NAME_DYNAMODB_TABLE_TASKS: !Ref "DynamodbRestaurantsTasks"
                NAME_TASK_REGISTER_PAGES: !Ref "TaskNameRegisterPages"
                NAME_TASK_SCRAPING_ABSTRACT: !Ref "TaskNameScrapingAbstract"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30