DynamodbRestaurantsTasksTmp:
    Type: "AWS::DynamoDB::Table"
    Properties:
        TableName: !If
            - "IsProd"
            - "RestaurantsTasksTmpProd"
            - "RestaurantsTasksTmpDev"
        AttributeDefinitions:
            - AttributeName: "kind"
              AttributeType: "S"
            - AttributeName: "params_id"
              AttributeType: "S"
        KeySchema:
            - AttributeName: "kind"
              KeyType: "HASH"
            - AttributeName: "params_id"
              KeyType: "RANGE"
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5