IamPolicyGetRestaurants:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsGetRestaurantsProd"
            - "RestaurantsGetRestaurantsDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                  Resource:
                      - !Sub "${DynamodbRestaurants.Arn}/index/MiddleAreaCodeLatitudeIndex"
                      - !Sub "${DynamodbRestaurants.Arn}/index/MiddleAreaCodeLongitudeIndex"
        Roles:
            - !Ref "IamRoleGetRestaurants"