IamPolicyErrorCommon:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsErrorCommonProd"
            - "RestaurantsErrorCommonDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - logs:DescribeLogStreams
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                  Resource: !GetAtt "CloudWatchLogGroup.Arn"
        Roles:
            - !Ref "IamRoleErrorCommon"