IamPolicyErrorCommon:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsErrorCommonProd"
            - "RestaurantsErrorCommonDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                      - "s3:ListBucket"
                  Resource:
                      - !GetAtt "S3ErrorLogs.Arn"
        Roles:
            - !Ref "IamRoleErrorCommon"