LambdaErrorCommon:
    Type: "AWS::Serverless::Function"
    Properties:
        Handler: app.lambda_handler
        CodeUri: "./lambda_functions/error_common/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsErrorCommonProd"
            - "RestaurantsErrorCommonDev"
        Role: !GetAtt "IamRoleErrorCommon.Arn"
        Environment:
            Variables:
                ARN_LAMBDA_LINE_NOTIFY: !GetAtt "LambdaLineNotify.Arn"
                NAME_S3_BUCKET_ERROR_LOGS: !Ref "S3ErrorLogs"
        Runtime: "python3.12"
        Architectures:
            - "arm64"
        Timeout: 30