LambdaRegisterTaskScrapingAbstractSmallAreas:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/register_task_scraping_abstract_small_areas/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsRegisterTaskScrapingAbstractSmallAreasProd"
            - "RestaurantsRegisterTaskScrapingAbstractSmallAreasDev"
        Role: !GetAtt "IamRoleRegisterTaskScrapingAbstractSmallAreas.Arn"
        Runtime: "python3.10"
        Environment:
            Variables:
                ARN_LAMBDA_LINE_NOTIFY: !GetAtt "LambdaLineNotify.Arn"
                ARN_LAMBDA_REGISTER_TASK_SCRAPING_ABSTRACT_PAGES: !GetAtt "LambdaRegisterTaskScrapingAbstractPages.Arn"
                ARN_INVOKE_REGISTER_TASK_SCRAPING_ABSTRACT_SMALL_AREAS: !GetAtt "IamRoleInvokeRegisterTaskScrapingAbstractSmallAreas.Arn"
                SCHEDULE_GROUP_NAME: !Ref "EventBridgeScheduleGroup"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30

        Events:
            EventBridgeScheduleLambdaRegisterTaskScrapingAbstract:
                Type: "ScheduleV2"
                Properties:
                    ScheduleExpression: cron(0 0 ? * SUN *)
                    ScheduleExpressionTimezone: "Asia/Tokyo"
                    State: ENABLED
                    GroupName: !Ref "EventBridgeScheduleGroup"
                    Name: !If
                        - "IsProd"
                        - "RestaurantsLambdaRegisterTaskScrapingAbstractSmallAreasProd"
                        - "RestaurantsLambdaRegisterTaskScrapingAbstractSmallAreasDev"
                    RoleArn: !GetAtt "IamRoleInvokeRegisterTaskScrapingAbstractSmallAreas.Arn"
                    Input: '{"middle_area_code": "Y883"}'