LambdaLayerDynamodbTypes:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
        LayerName: !If
            - "IsProd"
            - "RestaurantsDynamodbTypesProd"
            - "RestaurantsDynamodbTypesDev"
        ContentUri: "./lambda_layers/dynamodb_types/"
        CompatibleRuntimes:
            - "python3.12"